# debug_config = true

# Web Server Configuration
# These values can be overridden via environment variables or .env file using ${VAR_NAME} syntax
host_port = '8080'  # Can also use: '${HOST_PORT}' to load from env var
cache_bust = 'abc'
# log_file = './log.log'  # Can also use: '${LOG_FILE}'
log_level = 5                # 3 is recommended/default. Detail of logging (1-5): 1 is fatal-level only, 5 is trace-level detail. Level 3 is recommended for production.
cache_templates = false
ssl_disabled = true          # TURN OFF (set to false) IN PRODUCTION!!!
# ssl_cert_file = './tls/cert.pem'  # Can also use: '${SSL_CERT_FILE}'
# ssl_key_file = './tls/key.pem'    # Can also use: '${SSL_KEY_FILE}'

# Session/Cookie Configuration
secure_cookie_max_age = 0 # In seconds, e.g. 86400*7=604800; 0 means cookie persists for this session only
# Secure keys should be set via environment variables in production
# Use the values below for local development or override with ${ENV_VAR} syntax
secure_cookie_signing_key = '${SECURE_COOKIE_SIGNING_KEY}'
secure_cookie_encryption_key = '${SECURE_COOKIE_ENCRYPTION_KEY}'
regenerate_secure_keys = false # Set to `true` and execute the binary to generate keys and then exit
